sudo: false
dist: xenial
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=pylint
    - python: "3.7"
      env: TOXENV=py37
      sudo: true
    - python: "3.8"
      env: TOXENV=py38

cache: pip
install: pip install -U tox
language: python
script: travis_wait 40 tox --develop
