"""Tests for Sonoff ZBMINIR2 / MINI-ZBD quirks."""

import pytest
from unittest import mock
from zigpy.zcl import foundation
from zigpy.zcl.foundation import ZCLHeader, FrameControl, FrameType, Direction
import zigpy.types as t

from zhaquirks.sonoff.zbminir2 import (
    SonoffCluster,
    SonoffExternalSwitchTriggerType,
    InchingModeBit,
    RelaySperaKeyAction,
    INCHING_ENABLE_ATTR,
    INCHING_MODE_ATTR,
    INCHING_TIMEOUT_ATTR,
    SONOFF_MANUFACTURER_CODE,
    OnOff,
)
from tests.common import ClusterListener

try:
    from zigpy.zcl import ClusterType
except ImportError:
    try:
        from zigpy.zcl.foundation import ClusterType
    except ImportError:
        class ClusterType:
            Server = 0
            Client = 1


@pytest.fixture
def zbminir2_device(zigpy_device_from_v2_quirk):
    """Create a ZBMINIR2 device with the full quirk."""
    device = zigpy_device_from_v2_quirk(
        manufacturer="SONOFF",
        model="ZBMINIR2",
        cluster_ids={
            1: {
                SonoffCluster.cluster_id: ClusterType.Server,
            }
        },
    )
    return device


async def test_inching_write_attributes(zbminir2_device):
    """Test writing inching attributes triggers combined command and updates cache."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]

    with mock.patch.object(cluster, "_send_combined", mock.AsyncMock()) as mock_send:
        await cluster.write_attributes({"inching_enable": True})
        assert mock_send.call_count == 1
        assert cluster._inching_enable is True

        await cluster.write_attributes({"inching_mode": InchingModeBit.Auto_on})
        assert mock_send.call_count == 2
        assert cluster._inching_mode_bit == 1

        await cluster.write_attributes({"inching_timeout": 10})
        assert mock_send.call_count == 3
        assert cluster._inching_timeout == 10

        mock_send.reset_mock()
        await cluster.write_attributes({
            "inching_enable": False,
            "inching_mode": InchingModeBit.Auto_off,
            "inching_timeout": 5,
        })
        assert mock_send.call_count == 3


async def test_set_inching_payload(zbminir2_device):
    """Verify the manufacturer-specific command payload generated by set_inching."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]
    cluster._cmd_seq = 0

    mode = 0x81
    channel = 0
    timeout_units = 3000

    timeout_low = timeout_units & 0xFFFF
    timeout_high = (timeout_units >> 16) & 0xFFFF
    payload = bytearray([0x01, 0x17, 0x07, 0x80, mode, channel])
    payload.extend(timeout_low.to_bytes(2, 'little'))
    payload.extend(timeout_high.to_bytes(2, 'little'))
    checksum = 0
    for b in payload:
        checksum ^= b
    payload.append(checksum)

    hdr = ZCLHeader(
        frame_control=FrameControl(
            frame_type=FrameType.CLUSTER_COMMAND,
            is_manufacturer_specific=True,
            direction=Direction.Client_to_Server,
            disable_default_response=False,
            reserved=0,
        ),
        manufacturer=SONOFF_MANUFACTURER_CODE,
        tsn=1,
        command_id=0x01,
    )
    expected_data = hdr.serialize() + bytes(payload)

    with mock.patch.object(cluster.endpoint, "request", mock.AsyncMock()) as mock_req:
        await cluster.set_inching(mode=mode, channel=channel, timeout_units=timeout_units)

        assert mock_req.call_count == 1
        kwargs = mock_req.call_args[1]
        assert kwargs["cluster"] == SonoffCluster.cluster_id
        assert kwargs["sequence"] == 1
        assert kwargs["expect_reply"] is False
        assert kwargs["data"] == expected_data


async def test_handle_message_inching_report(zbminir2_device):
    """Test parsing incoming manufacturer-specific inching report."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]
    listener = ClusterListener(cluster)

    report_payload = bytes([
        0x01, 0x17, 0x01,
        0x80,
        0x00,
        0x81,
        0x05, 0x00, 0x00, 0x00
    ])
    hdr = ZCLHeader(
        frame_control=FrameControl(
            frame_type=FrameType.CLUSTER_COMMAND,
            is_manufacturer_specific=True,
            direction=Direction.Server_to_Client,
            disable_default_response=False,
            reserved=0,
        ),
        manufacturer=SONOFF_MANUFACTURER_CODE,
        tsn=0x12,
        command_id=0x01,
    )
    cluster.handle_message(hdr, report_payload)

    assert cluster._inching_enable is True
    assert cluster._inching_mode_bit == 1
    assert cluster._inching_timeout == 5

    assert len(listener.attribute_updates) == 3
    assert listener.attribute_updates[0] == (INCHING_ENABLE_ATTR, True)
    assert listener.attribute_updates[1] == (INCHING_MODE_ATTR, 1)
    assert listener.attribute_updates[2] == (INCHING_TIMEOUT_ATTR, 5)


async def test_relay_detach_key_event(zbminir2_device):
    """Test that relay_spera_key_action_event attribute updates emit ZHA_SEND_EVENT."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]
    listener = mock.MagicMock()
    cluster.add_listener(listener)

    cluster.update_attribute(0x0028, RelaySperaKeyAction.Double_click)
    assert listener.zha_send_event.call_count == 1
    listener.zha_send_event.assert_called_with("Double_click", {})

    listener.reset_mock()
    cluster.update_attribute(0x0028, 99)
    assert listener.zha_send_event.call_count == 1
    listener.zha_send_event.assert_called_with("undefined_0x63", {})


async def test_inching_write_failure_does_not_revert_cache(zbminir2_device):
    """
    Test that even if _send_combined raises an exception, the local cache is updated.
    This documents current behavior; we may later decide to revert on failure.
    """
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]

    with mock.patch.object(cluster, "_send_combined", mock.AsyncMock(side_effect=Exception("Comm error"))):
        with pytest.raises(Exception, match="Comm error"):
            await cluster.write_attributes({"inching_mode": 1})
        assert cluster._inching_mode_bit == 1


async def test_non_inching_attributes_write(zbminir2_device):
    """Test writing non-inching attributes works normally."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]

    with mock.patch.object(
        cluster, "write_attributes_raw", mock.AsyncMock(return_value=[[
            foundation.WriteAttributesStatusRecord(
                status=foundation.Status.SUCCESS,
                attrid=0x0017,
            )
        ]])
    ) as mock_raw:
        await cluster.write_attributes({"detach_relay": True})
        assert mock_raw.call_count == 1
        assert cluster._attr_cache.get(0x0017) is True

    with mock.patch.object(
        cluster, "write_attributes_raw", mock.AsyncMock(return_value=[[
            foundation.WriteAttributesStatusRecord(
                status=foundation.Status.SUCCESS,
                attrid=0x0016,
            )
        ]])
    ):
        await cluster.write_attributes({"external_trigger_mode": SonoffExternalSwitchTriggerType.Pulse_trigger})
        assert cluster._attr_cache.get(0x0016) == SonoffExternalSwitchTriggerType.Pulse_trigger


async def test_initial_attribute_defaults(zbminir2_device):
    """Test that inching attributes are seeded with default values."""
    cluster = zbminir2_device.endpoints[1].in_clusters[SonoffCluster.cluster_id]
    assert cluster._inching_enable is False
    assert cluster._inching_mode_bit == 0
    assert cluster._inching_timeout == 2


async def test_device_automation_triggers(zbminir2_device):
    """Verify that device_automation_triggers are correctly defined."""
    triggers = zbminir2_device.device_automation_triggers
    assert triggers is not None
    assert ("External Switch action", "Single Click") in triggers
    assert ("External Switch action", "Double Click") in triggers
    assert ("External Switch action", "Long Press") in triggers

    trigger_def = triggers[("External Switch action", "Double Click")]
    assert trigger_def["cluster_id"] == SonoffCluster.cluster_id
    assert trigger_def["endpoint_id"] == 1
    assert trigger_def["command"] == "Double_click"


async def test_onoff_toggle_triggers_single_click(zbminir2_device):
    """Test that toggle command from OnOff cluster triggers Single_click event."""
    endpoint = zbminir2_device.endpoints[1]
    onoff_cluster = endpoint.in_clusters[0x0006]
    sonoff_cluster = endpoint.in_clusters[SonoffCluster.cluster_id]

    listener = mock.MagicMock()
    sonoff_cluster.add_listener(listener)

    hdr = ZCLHeader(
        frame_control=FrameControl(
            frame_type=FrameType.CLUSTER_COMMAND,
            is_manufacturer_specific=False,
            direction=Direction.Server_to_Client,
            disable_default_response=False,
            reserved=0,
        ),
        manufacturer=None,
        tsn=0x01,
        command_id=OnOff.ServerCommandDefs.toggle.id,
    )
    onoff_cluster.handle_cluster_request(hdr, b"")

    listener.zha_send_event.assert_called_once_with("Single_click", {})
    # 属性缓存存储的是枚举名称字符串，而非数值
    assert sonoff_cluster._attr_cache.get(0x0028) == RelaySperaKeyAction.Single_click.name