name: Device support request
description: Request support for an unsupported device or a missing device feature.
title: "[Device Support Request] "
body:
  - type: markdown
    attributes:
      value: |
        Before filing an issue, please try to reproduce your problem using the latest Home Assistant release.
        Also, search the [existing issues](https://github.com/zigpy/zha-device-handlers/issues) to see if your device  has already been reported.
        If you have a question, please use [GitHub discussions](https://github.com/zigpy/zha-device-handlers/discussions).
        
        If you're using custom quirks, remove them first. Then, restart HA and check if the issue persists.
        Lastly, make sure to give your issue a descriptive title.
  - type: markdown
    attributes:
      value: |
        # General information
  - type: textarea
    attributes:
      label: Problem description
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution description
      description: Please describe what solution you would like.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Video
      description: |
        If helpful, you can upload screenshots or videos relevant to your feature request.
      value: |
        <details><summary>Screenshots/Video</summary>

        [Paste/upload your media here]

        </details>
  - type: markdown
    attributes:
      value: |
        # Debug information
  - type: textarea
    attributes:
      label: Device signature
      description: |
        You can find the device signature by going to the device page, clicking the three dots, clicking on "Manage Zigbee device", and then selecting the "Signature" tab at the top.
        
        Copy the contents and paste your device signature in between the lines with the backticks below.
      value: |
        <details><summary>Device signature</summary>

        ```json
        [Paste the device signature here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Diagnostic information
      description: |
        You can find the diagnostic information of the device by going to the device page, clicking the three dots, and then by clicking on "Download diagnostics".
        
        Copy the contents of the downloaded text file and paste it in between the lines with the backticks below.
      value: |
        <details><summary>Diagnostic information</summary>

        ```json
        [Paste the diagnostic information here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Logs
      description: |
        If applicable, you can upload relevant logs here.
        In some cases, it's helpful to enable debug logging, reproducing the issue again, and then uploading the logs.
        
        Note: To enable debug logging, see [this section](https://www.home-assistant.io/integrations/zha/#debug-logging), then restart Home Assistant, reproduce the issue again, and paste the relevant logs in between the lines with the backticks below.
        
        You can also enable debug logs at runtime by going to the integrations page in settings, clicking the three dots next to your ZHA integration, and selecting "Enable debug logging".
        Reproduce the issue again, click on those three dots again, and select "Disable debug logging".
        Then, copy the relevant log parts from the downloaded file and paste them in between the lines with the backticks below.
      value: |
        <details><summary>Logs</summary>

        ```python
        [Paste the logs here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Custom quirk
      description: |
        If you've started working on a custom quirk, paste it in between the lines with the backticks below.
      value: |
        <details><summary>Custom quirk</summary>

        ```python
        [Paste your custom quirk here]
        ```

        </details>
  - type: textarea
    attributes:
      label: Additional information
      description: |
        If you have additional information or context about the feature request, provide it here.
