"""ElectSmart BHT-009 Thermostat quirk."""

# Generated by migrating from z2m herdsman
# https://github.com/Koenkk/zigbee-herdsman-converters/blob/e5bb673eaaca70058c0aebf75631e23a2741ed9b/src/devices/tuya.ts#L18747
# Supports most features, except the schedule function.

from zigpy.quirks.v2 import NumberDeviceClass
from zigpy.quirks.v2.homeassistant import UnitOfTemperature
import zigpy.types as t
from zigpy.zcl.clusters.hvac import RunningState, Thermostat

from zhaquirks.tuya.builder import TuyaQuirkBuilder
from zhaquirks.tuya.mcu import TuyaAttributesCluster


class OperationMode(t.enum8):
    Scheduled = 0x00
    Manual = 0x01


class HeatingStatus(t.enum8):
    Heating = 0x00
    Idle = 0x01


class SensorMode(t.enum8):
    IN = 0x00
    AL = 0x01
    OU = 0x02

class ElectSmartTuyaThermostat(Thermostat, TuyaAttributesCluster):
    """Tuya local thermostat cluster."""

    _CONSTANT_ATTRIBUTES = {
        Thermostat.AttributeDefs.ctrl_sequence_of_oper.id: Thermostat.ControlSequenceOfOperation.Heating_Only
    }

    def __init__(self, *args, **kwargs):
        """Init a TuyaThermostat cluster."""
        super().__init__(*args, **kwargs)
        self.add_unsupported_attribute(
            Thermostat.AttributeDefs.setpoint_change_source.id
        )
        self.add_unsupported_attribute(
            Thermostat.AttributeDefs.setpoint_change_source_timestamp.id
        )
        self.add_unsupported_attribute(Thermostat.AttributeDefs.pi_heating_demand.id)


(
    TuyaQuirkBuilder("_TZE204_tagezcph", "TS0601")
    .applies_to("_TZE204_tagezcph", "TS0601")
    .tuya_dp(
        dp_id=1,
        ep_attribute=ElectSmartTuyaThermostat.ep_attribute,
        attribute_name=ElectSmartTuyaThermostat.AttributeDefs.system_mode.name,
        converter=lambda x: {
            True: Thermostat.SystemMode.Heat,
            False: Thermostat.SystemMode.Off,
        }[x],
        dp_converter=lambda x: {
            Thermostat.SystemMode.Heat: True,
            Thermostat.SystemMode.Off: False,
        }[x],
    )
    .tuya_enum(
        dp_id=2,
        attribute_name="preset_mode",
        enum_class=OperationMode,
        translation_key="preset_mode",
        fallback_name="Preset mode",
    )
    .tuya_temperature(dp_id=24, scale=10)
    .tuya_dp(
        dp_id=16,
        ep_attribute=ElectSmartTuyaThermostat.ep_attribute,
        attribute_name=ElectSmartTuyaThermostat.AttributeDefs.occupied_heating_setpoint.name,
        converter=lambda x: x * 10,  # Convert from 0.1°C to 0.01°C
        dp_converter=lambda x: x // 10,  # Convert from 0.01°C to 0.1°C
    )
    .tuya_number(
        dp_id=26,
        attribute_name="min_temperature",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=5.0,
        max_value=15.0,
        step=1.0,
        multiplier=0.1,
        translation_key="min_temperature",
        fallback_name="Minimum temperature",
    )
    .tuya_number(
        dp_id=19,
        attribute_name="max_temperature",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=15.0,
        max_value=45.0,
        step=1.0,
        multiplier=0.1,
        translation_key="max_temperature",
        fallback_name="Maximum temperature",
    )
    .tuya_number(
        dp_id=111,
        attribute_name="min_temperature_limit",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=0.0,
        max_value=10.0,
        step=1.0,
        multiplier=0.1,
        translation_key="min_temperature_limit",
        fallback_name="Low temperature protection",
    )
    .tuya_number(
        dp_id=104,
        attribute_name="max_temperature_limit",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=25.0,
        max_value=70.0,
        step=1.0,
        multiplier=0.1,
        translation_key="max_temperature_limit",
        fallback_name="High temperature protection",
    )
    .tuya_number(
        dp_id=112,
        attribute_name="eco_temperature",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=5.0,
        max_value=30.0,
        step=1.0,
        multiplier=0.1,
        translation_key="eco_temperature",
        fallback_name="Eco temperature",
    )
    .tuya_number(
        dp_id=103,
        attribute_name="deadzone_temperature",
        type=t.uint16_t,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        min_value=1.0,
        max_value=5.0,
        step=1.0,
        multiplier=1.0,
        translation_key="deadzone_temperature",
        fallback_name="Deadzone temperature",
    )
    .tuya_sensor(
        dp_id=102,
        attribute_name="external_temperature_input",
        type=t.int16s,
        device_class=NumberDeviceClass.TEMPERATURE,
        unit=UnitOfTemperature.CELSIUS,
        multiplier=0.1,
        translation_key="external_temperature_input",
        fallback_name="Floor temperature",
    )
    .tuya_enum(
        dp_id=43,
        attribute_name="sensor",
        enum_class=SensorMode,
        translation_key="sensor",
        fallback_name="Sensor",
    )
    .tuya_dp(
        dp_id=36,
        ep_attribute=ElectSmartTuyaThermostat.ep_attribute,
        attribute_name=ElectSmartTuyaThermostat.AttributeDefs.running_state.name,
        converter=lambda x: RunningState.Heat_State_On if x == HeatingStatus.Heating else RunningState.Idle,
    )
    .tuya_switch(
        dp_id=39,
        attribute_name="child_lock",
        translation_key="child_lock",
        fallback_name="Child lock",
    )
    .tuya_switch(
        dp_id=40,
        attribute_name="eco_mode",
        translation_key="eco_mode",
        fallback_name="Eco mode",
    )
    .adds(ElectSmartTuyaThermostat)
    .skip_configuration()
    .add_to_registry()
)