"""Module for Profalux quirks implementations."""
MANUFACTURER_SPECIFIC_CLUSTER_ID_1 = 0xFC20  # decimal = 64544
MANUFACTURER_SPECIFIC_CLUSTER_ID_2 = 0xFC21  # decimal = 64545
PROFALUX_MANUFACTURER = "PROFALUX"
PROFALUX_MODEL_COVER = "Cover"
PROFALUX_MODEL_REMOTE = "Remote"